### ISSUE TITLE
PHP doesn't get installed

### ISSUE THREAD

**Issue by StefanDi** [MiniCodeMonkey/Vagrant-LAMP-Stack#29]
Just getting errors. 2 month before it was working :(
1. ==> tuto: stdin: is not a tty
2. ==> tuto: Error executing action `install` on resource 'package[php5-dev]'
   ...
3. ==> tuto: Ran apt-get -q -y install php5-dev=5.4.32-1~dotdeb.0 returned 100
4. ==> tuto: [2014-08-23T22:09:40+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
   Chef never successfully completed! Any errors should be visible in the output above. Please fix your recipes so that they properly complete.

Anyone know how to fix it? Thank you.

**Comment by KyleColyer** [comment]
Same here. First attempt at using Vagrant and clueless :(

**Comment by pyhub** [comment]
## still an issue. cant install php.

==> lampstack: [2014-09-29T17:00:10+00:00] WARN: In a future Chef release, 'manage_symlink_source' will not be enabled by default
==> lampstack: [2014-09-29T17:00:10+00:00] WARN: File /usr/sbin/a2enconf managed by template[/usr/sbin/a2enconf] is really a symlink. Managing the source file instead.
==> lampstack: [2014-09-29T17:00:10+00:00] WARN: Disable this warning by setting `manage_symlink_source true` on the resource
==> lampstack: [2014-09-29T17:00:10+00:00] WARN: In a future Chef release, 'manage_symlink_source' will not be enabled by default
==> lampstack: [2014-09-29T17:00:10+00:00] WARN: File /usr/sbin/a2disconf managed by template[/usr/sbin/a2disconf] is really a symlink. Managing the source file instead.
==> lampstack: [2014-09-29T17:00:10+00:00] WARN: Disable this warning by setting `manage_symlink_source true` on the resource
==> lampstack: [2014-09-29T17:00:10+00:00] WARN: In a future Chef release, 'manage_symlink_source' will not be enabled by default
==> lampstack: [2014-09-29T17:00:10+00:00] INFO: template[/usr/sbin/a2disconf] backed up to /var/chef/backup/usr/sbin/a2disconf.chef-20140929170010
==> lampstack: [2014-09-29T17:00:10+00:00] INFO: template[/usr/sbin/a2disconf] updated file contents /usr/sbin/a2disconf
==> lampstack: 
==> lampstack: ================================================================================
==> lampstack: Error executing action `install` on resource 'package[php5-mcrypt]'
==> lampstack: ================================================================================
==> lampstack: 
==> lampstack: 
==> lampstack: Chef::Exceptions::Exec
==> lampstack: ----------------------
==> lampstack: apt-get -q -y install php5-mcrypt=5.4.33-1~dotdeb.0 returned 100, expected 0
==> lampstack: 
==> lampstack: 
==> lampstack: Resource Declaration:
==> lampstack: ---------------------
==> lampstack: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/app/recipes/web_server.rb
==> lampstack: 
==> lampstack:  22:   package a_package
==> lampstack:  23: end
==> lampstack: 
==> lampstack: 
==> lampstack: 
==> lampstack: Compiled Resource:
==> lampstack: ------------------
==> lampstack: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/app/recipes/web_server.rb:22:in `block in from_file'
==> lampstack: 
==> lampstack: package("php5-mcrypt") do
==> lampstack:   action :install
==> lampstack:   retries 0
==> lampstack:   retry_delay 2
==> lampstack:   package_name "php5-mcrypt"
==> lampstack:   version "5.4.33-1~dotdeb.0"
==> lampstack:   cookbook_name :app
==> lampstack:   recipe_name "web_server"
==> lampstack: end
==> lampstack: 
==> lampstack: 
==> lampstack: 
==> lampstack: [2014-09-29T17:00:24+00:00] INFO: Running queued delayed notifications before re-raising exception
==> lampstack: [2014-09-29T17:00:24+00:00] ERROR: Running exception handlers
==> lampstack: [2014-09-29T17:00:24+00:00] ERROR: Exception handlers complete
==> lampstack: [2014-09-29T17:00:24+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> lampstack: [2014-09-29T17:00:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the

## output above. Please fix your recipes so that they properly complete.

**Comment by LeKlex** [comment]
Hi!
Having the same problem :-/
Since some days I can't get up any of my VMs, and bringing up a new one (fresh clone from repo) ends up in:

```
==> projectname: STDERR: Creating config file /etc/php5/mods-available/pdo.ini with new version
==> projectname: Replacing config file /etc/php5/cli/php.ini with new version
==> projectname:
==> projectname: Configuration file `/etc/apache2/mods-available/php5.conf'
==> projectname:  ==> Modified (by you or by a script) since installation.
==> projectname:  ==> Package distributor has shipped an updated version.
==> projectname:    What would you like to do about it ?  Your options are:
==> projectname:     Y or I  : install the package maintainer's version
==> projectname:     N or O  : keep your currently-installed version
==> projectname:       D     : show the differences between the versions
==> projectname:       Z     : start a shell to examine the situation
==> projectname:  The default action is to keep your current version.
==> projectname: *** php5.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing libapache2-mod-php5 (--configure):
==> projectname:  EOF on stdin at conffile prompt
==> projectname:
==> projectname: Creating config file /etc/php5/cgi/php.ini with new version
==> projectname: Errors were encountered while processing:
==> projectname:  libapache2-mod-php5
==> projectname: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> projectname: ---- End output of apt-get -q -y install php5-cgi=5.4.33-1~dotdeb.0 ----
==> projectname: Ran apt-get -q -y install php5-cgi=5.4.33-1~dotdeb.0 returned 100
==> projectname: [2014-10-02T17:48:57+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

--EDIT:
Vagrant 1.5.4
Berkshelf 3.1.1

After removing .vagrant and .berkshelf and some up/destroy/provision now I ran into

```
[2014-10-03T09:32:27+00:00] INFO: *** Chef 11.16.2 ***
[2014-10-03T09:32:27+00:00] INFO: Chef-client pid: 15819
[2014-10-03T09:32:29+00:00] INFO: Setting the run_list to ["recipe[app::packages]", "recipe[app::web_server]", "recipe[app::vhost]", "recipe[memcached]", "recipe[app::db]"] from CLI options
[2014-10-03T09:32:29+00:00] INFO: Run List is [recipe[app::packages], recipe[app::web_server], recipe[app::vhost], recipe[memcached], recipe[app::db]]
[2014-10-03T09:32:29+00:00] INFO: Run List expands to [app::packages, app::web_server, app::vhost, memcached, app::db]
[2014-10-03T09:32:29+00:00] INFO: Starting Chef Run for market.local
[2014-10-03T09:32:29+00:00] INFO: Running start handlers
[2014-10-03T09:32:29+00:00] INFO: Start handlers complete.
[2014-10-03T09:32:30+00:00] INFO: WindowsPackage lightweight resource already initialized -- overriding!
[2014-10-03T09:32:35+00:00] INFO: bash[fix-phpcomments] ran successfully
[2014-10-03T09:32:39+00:00] INFO: bash[composer] ran successfully

================================================================================
Error executing action `start` on resource 'service[mysql]'
================================================================================

Chef::Exceptions::Exec
----------------------
/sbin/start mysql returned 1, expected 0

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service_ubuntu.rb

 58:             service 'mysql' do
 59:               provider Chef::Provider::Service::Upstart
 60:               supports :restart => true
 61:               action [:start, :enable]
 62:             end
 63:

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service_ubuntu.rb:58:in `block (2 levels) in <class:Ubuntu>'

service("mysql") do
  provider Chef::Provider::Service::Upstart
  action [:start, :enable]
  supports {:restart=>true}
  retries 0
  retry_delay 2
  guard_interpreter :default
  service_name "mysql"
  pattern "mysql"
  cookbook_name :mysql
end

[2014-10-03T09:32:40+00:00] INFO: Running queued delayed notifications before re-raising exception

================================================================================
Error executing action `create` on resource 'mysql_service[default]'
================================================================================

Chef::Exceptions::Exec
----------------------
service[mysql] (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service_ubuntu.rb line 58) had an error: Chef::Exceptions::Exec: /sbin/start mysql returned 1, expected 0

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/recipes/server.rb

 20: mysql_service node['mysql']['service_name'] do
 21:   port node['mysql']['port']
 22:   data_dir node['mysql']['data_dir']
 23:   server_root_password node['mysql']['server_root_password']
 24:   server_debian_password node['mysql']['server_debian_password']
 25:   server_repl_password node['mysql']['server_repl_password']
 26:   allow_remote_root node['mysql']['allow_remote_root']
 27:   remove_anonymous_users node['mysql']['remove_anonymous_users']
 28:   remove_test_database node['mysql']['remove_test_database']
 29:   root_network_acl node['mysql']['root_network_acl']
 30:   action :create
 31: end

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/recipes/server.rb:20:in `from_file'

mysql_service("default") do
  action [:create]
  retries 0
  retry_delay 2
  guard_interpreter :default
  service_name "default"
  version "5.5"
  package_name "mysql-server-5.5"
  data_dir "/var/lib/mysql"
  port "3306"
  allow_remote_root true
  remove_anonymous_users true
  remove_test_database true
  server_root_password "root"
  server_debian_password "root"
  server_repl_password "root"
  cookbook_name :mysql
  recipe_name "server"
end

[2014-10-03T09:32:40+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-10-03T09:32:40+00:00] INFO: bash[fix-phpcomments] sending restart action to service[apache2] (delayed)
[2014-10-03T09:32:42+00:00] INFO: service[apache2] restarted
[2014-10-03T09:32:42+00:00] ERROR: Running exception handlers
[2014-10-03T09:32:42+00:00] ERROR: Exception handlers complete
[2014-10-03T09:32:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-10-03T09:32:42+00:00] ERROR: mysql_service[default] (mysql::server line 20) had an error: Chef::Exceptions::Exec: service[mysql] (/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mysql/libraries/provider_mysql_service_ubuntu.rb line 58) had an error: Chef::Exceptions::Exec: /sbin/start mysql returned 1, expected 0
[2014-10-03T09:32:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should ....
```
